`timescale 1ps/100fs
// Simulation wrapper for lscc_pll CoCoTB testbench.
// Provides GSR_INST at the top level and exposes all DUT ports and parameters for cocotb to drive.

module testgen_top #(
    parameter                     FVCO                     = 800.0,
    parameter                     FVCO_STR                 = "800.0",
    parameter                     CLKI_FREQ                = 100.0,
    parameter                     CLKI_FREQ_STR            = "100.0",
    parameter                     CLKOP_FREQ_ACTUAL        = 100.0,
    parameter                     CLKOS_FREQ_ACTUAL        = 100.0,
    parameter                     CLKOS2_FREQ_ACTUAL       = 100.0,
    parameter                     CLKOS3_FREQ_ACTUAL       = 100.0,
    parameter                     CLKOS4_FREQ_ACTUAL       = 100.0,
    parameter                     CLKOS5_FREQ_ACTUAL       = 100.0,
    parameter                     CLKOP_PHASE_ACTUAL       = 0.0,
    parameter                     CLKOS_PHASE_ACTUAL       = 0.0,
    parameter                     CLKOS2_PHASE_ACTUAL      = 0.0,
    parameter                     CLKOS3_PHASE_ACTUAL      = 0.0,
    parameter                     CLKOS4_PHASE_ACTUAL      = 0.0,
    parameter                     CLKOS5_PHASE_ACTUAL      = 0.0,
    parameter                     CLKOS_EN                 = 0,
    parameter                     CLKOS2_EN                = 0,
    parameter                     CLKOS3_EN                = 0,
    parameter                     CLKOS4_EN                = 0,
    parameter                     CLKOS5_EN                = 0,
    parameter                     CLKOP_BYPASS             = 0,
    parameter                     CLKOS_BYPASS             = 0,
    parameter                     CLKOS2_BYPASS            = 0,
    parameter                     CLKOS3_BYPASS            = 0,
    parameter                     CLKOS4_BYPASS            = 0,
    parameter                     CLKOS5_BYPASS            = 0,
    parameter                     ENCLKOP_EN               = 0,
    parameter                     ENCLKOS_EN               = 0,
    parameter                     ENCLKOS2_EN              = 0,
    parameter                     ENCLKOS3_EN              = 0,
    parameter                     ENCLKOS4_EN              = 0,
    parameter                     ENCLKOS5_EN              = 0,
    parameter                     FRAC_N_EN                = 0,
    parameter                     SS_EN                    = 0,
    parameter                     DYN_PORTS_EN             = 0,
    parameter                     PLL_RST                  = 1,
    parameter                     LOCK_EN                  = 1,
    parameter                     PLL_LOCK_STICKY          = 0,
    parameter                     LEGACY_EN                = 0,
    parameter                     LMMI_EN                  = 0,
    parameter                     APB_EN                   = 0,
    parameter                     APB_SOFT_REG_EN          = 0,
    parameter                     POWERDOWN_EN             = 0,
    parameter                     TRIM_EN_P                = 0,
    parameter                     TRIM_EN_S                = 0,
    parameter                     PLL_REFCLK_FROM_PIN      = 0,
    parameter                     IO_TYPE                  = "LVDS",
    parameter                     CLKOP_TRIM_MODE          = "Falling",
    parameter                     CLKOS_TRIM_MODE          = "Falling",
    parameter                     CLKOP_TRIM               = "0b0000",
    parameter                     CLKOS_TRIM               = "0b0000",
    parameter                     FBK_MODE                 = "CLKOP",
    parameter                     CLKI_DIVIDER_ACTUAL_STR  = "1",
    parameter                     FBCLK_DIVIDER_ACTUAL_STR = "1",
    parameter                     DIVOP_ACTUAL_STR         = "1",
    parameter                     DIVOS_ACTUAL_STR         = "1",
    parameter                     DIVOS2_ACTUAL_STR        = "1",
    parameter                     DIVOS3_ACTUAL_STR        = "1",
    parameter                     DIVOS4_ACTUAL_STR        = "1",
    parameter                     DIVOS5_ACTUAL_STR        = "1",
    parameter                     SSC_N_CODE_STR           = "0b000010100",
    parameter                     SSC_F_CODE_STR           = "0b000000000000000",
    parameter                     SSC_PROFILE              = "DOWN",
    parameter                     SSC_TBASE_STR            = "0b000000000000",
    parameter                     SSC_STEP_IN_STR          = "0b0000000",
    parameter                     SSC_REG_WEIGHTING_SEL_STR= "0b000",
    parameter                     DELA                     = "0",
    parameter                     DELB                     = "0",
    parameter                     DELC                     = "0",
    parameter                     DELD                     = "0",
    parameter                     DELE                     = "0",
    parameter                     DELF                     = "0",
    parameter                     PHIA                     = "0",
    parameter                     PHIB                     = "0",
    parameter                     PHIC                     = "0",
    parameter                     PHID                     = "0",
    parameter                     PHIE                     = "0",
    parameter                     PHIF                     = "0",
    parameter                     EN_REFCLK_MON            = 0,
    parameter                     REF_COUNTS               = "0000",
    parameter                     INTFBKDEL_SEL            = "DISABLED",
    parameter                     PMU_WAITFORLOCK          = "ENABLED",
    parameter                     REF_OSC_CTRL             = "3P2",
    parameter                     SIM_FLOAT_PRECISION      = "0.625",
    parameter                     IPI_CMP                  = "0b1000",
    parameter                     CSET                     = "40P",
    parameter                     CRIPPLE                  = "5P",
    parameter                     IPP_CTRL                 = "0b1000",
    parameter                     IPP_SEL                  = "0b1111",
    parameter                     BW_CTL_BIAS              = "0b0101",
    parameter                     V2I_PP_RES               = "10K",
    parameter                     KP_VCO                   = "0b00011",
    parameter                     V2I_KVCO_SEL             = "60",
    parameter                     V2I_1V_EN                = "ENABLED"
) (
    input  wire                   rstn_i,
    input  wire                   clki_i,
    input  wire                   usr_fbclk_i,

    input  wire                   phasedir_i,
    input  wire                   phasestep_i,
    input  wire                   phaseloadreg_i,
    input  wire [2:0]             phasesel_i,

    input  wire                   enclkop_i,
    input  wire                   enclkos_i,
    input  wire                   enclkos2_i,
    input  wire                   enclkos3_i,
    input  wire                   enclkos4_i,
    input  wire                   enclkos5_i,

    output wire                   clkop_o,
    output wire                   clkos_o,
    output wire                   clkos2_o,
    output wire                   clkos3_o,
    output wire                   clkos4_o,
    output wire                   clkos5_o,

    output wire                   lock_o,

    input  wire                   pllpd_en_n_i,
    input  wire                   legacy_i,

    input  wire                   refdetreset,
    output wire                   refdetlos,

    input  wire                   lmmi_clk_i,
    input  wire                   lmmi_resetn_i,
    input  wire                   lmmi_request_i,
    input  wire                   lmmi_wr_rdn_i,
    input  wire [6:0]             lmmi_offset_i,
    input  wire [7:0]             lmmi_wdata_i,
    output wire                   lmmi_ready_o,
    output wire                   lmmi_rdata_valid_o,
    output wire [7:0]             lmmi_rdata_o,

    input  wire                   apb_pclk_i,
    input  wire                   apb_preset_n_i,
    input  wire                   apb_penable_i,
    input  wire                   apb_psel_i,
    input  wire                   apb_pwrite_i,
    input  wire [31:0]            apb_paddr_i,
    input  wire [31:0]            apb_pwdata_i,
    output wire                   apb_pready_o,
    output wire                   apb_pslverr_o,
    output wire [31:0]            apb_prdata_o
);

    GSR GSR_INST (.GSR_N(1'b1), .CLK(1'b0));

    lscc_pll #(
        .FVCO                     (FVCO),
        .FVCO_STR                 (FVCO_STR),
        .CLKI_FREQ                (CLKI_FREQ),
        .CLKI_FREQ_STR            (CLKI_FREQ_STR),
        .CLKOP_FREQ_ACTUAL        (CLKOP_FREQ_ACTUAL),
        .CLKOS_FREQ_ACTUAL        (CLKOS_FREQ_ACTUAL),
        .CLKOS2_FREQ_ACTUAL       (CLKOS2_FREQ_ACTUAL),
        .CLKOS3_FREQ_ACTUAL       (CLKOS3_FREQ_ACTUAL),
        .CLKOS4_FREQ_ACTUAL       (CLKOS4_FREQ_ACTUAL),
        .CLKOS5_FREQ_ACTUAL       (CLKOS5_FREQ_ACTUAL),
        .CLKOP_PHASE_ACTUAL       (CLKOP_PHASE_ACTUAL),
        .CLKOS_PHASE_ACTUAL       (CLKOS_PHASE_ACTUAL),
        .CLKOS2_PHASE_ACTUAL      (CLKOS2_PHASE_ACTUAL),
        .CLKOS3_PHASE_ACTUAL      (CLKOS3_PHASE_ACTUAL),
        .CLKOS4_PHASE_ACTUAL      (CLKOS4_PHASE_ACTUAL),
        .CLKOS5_PHASE_ACTUAL      (CLKOS5_PHASE_ACTUAL),
        .CLKOS_EN                 (CLKOS_EN),
        .CLKOS2_EN                (CLKOS2_EN),
        .CLKOS3_EN                (CLKOS3_EN),
        .CLKOS4_EN                (CLKOS4_EN),
        .CLKOS5_EN                (CLKOS5_EN),
        .CLKOP_BYPASS             (CLKOP_BYPASS),
        .CLKOS_BYPASS             (CLKOS_BYPASS),
        .CLKOS2_BYPASS            (CLKOS2_BYPASS),
        .CLKOS3_BYPASS            (CLKOS3_BYPASS),
        .CLKOS4_BYPASS            (CLKOS4_BYPASS),
        .CLKOS5_BYPASS            (CLKOS5_BYPASS),
        .ENCLKOP_EN               (ENCLKOP_EN),
        .ENCLKOS_EN               (ENCLKOS_EN),
        .ENCLKOS2_EN              (ENCLKOS2_EN),
        .ENCLKOS3_EN              (ENCLKOS3_EN),
        .ENCLKOS4_EN              (ENCLKOS4_EN),
        .ENCLKOS5_EN              (ENCLKOS5_EN),
        .FRAC_N_EN                (FRAC_N_EN),
        .SS_EN                    (SS_EN),
        .DYN_PORTS_EN             (DYN_PORTS_EN),
        .PLL_RST                  (PLL_RST),
        .LOCK_EN                  (LOCK_EN),
        .PLL_LOCK_STICKY          (PLL_LOCK_STICKY),
        .LEGACY_EN                (LEGACY_EN),
        .LMMI_EN                  (LMMI_EN),
        .APB_EN                   (APB_EN),
        .APB_SOFT_REG_EN          (APB_SOFT_REG_EN),
        .POWERDOWN_EN             (POWERDOWN_EN),
        .TRIM_EN_P                (TRIM_EN_P),
        .TRIM_EN_S                (TRIM_EN_S),
        .PLL_REFCLK_FROM_PIN      (PLL_REFCLK_FROM_PIN),
        .IO_TYPE                  (IO_TYPE),
        .CLKOP_TRIM_MODE          (CLKOP_TRIM_MODE),
        .CLKOS_TRIM_MODE          (CLKOS_TRIM_MODE),
        .CLKOP_TRIM               (CLKOP_TRIM),
        .CLKOS_TRIM               (CLKOS_TRIM),
        .FBK_MODE                 (FBK_MODE),
        .CLKI_DIVIDER_ACTUAL_STR  (CLKI_DIVIDER_ACTUAL_STR),
        .FBCLK_DIVIDER_ACTUAL_STR (FBCLK_DIVIDER_ACTUAL_STR),
        .DIVOP_ACTUAL_STR         (DIVOP_ACTUAL_STR),
        .DIVOS_ACTUAL_STR         (DIVOS_ACTUAL_STR),
        .DIVOS2_ACTUAL_STR        (DIVOS2_ACTUAL_STR),
        .DIVOS3_ACTUAL_STR        (DIVOS3_ACTUAL_STR),
        .DIVOS4_ACTUAL_STR        (DIVOS4_ACTUAL_STR),
        .DIVOS5_ACTUAL_STR        (DIVOS5_ACTUAL_STR),
        .SSC_N_CODE_STR           (SSC_N_CODE_STR),
        .SSC_F_CODE_STR           (SSC_F_CODE_STR),
        .SSC_PROFILE              (SSC_PROFILE),
        .SSC_TBASE_STR            (SSC_TBASE_STR),
        .SSC_STEP_IN_STR          (SSC_STEP_IN_STR),
        .SSC_REG_WEIGHTING_SEL_STR(SSC_REG_WEIGHTING_SEL_STR),
        .DELA                     (DELA),
        .DELB                     (DELB),
        .DELC                     (DELC),
        .DELD                     (DELD),
        .DELE                     (DELE),
        .DELF                     (DELF),
        .PHIA                     (PHIA),
        .PHIB                     (PHIB),
        .PHIC                     (PHIC),
        .PHID                     (PHID),
        .PHIE                     (PHIE),
        .PHIF                     (PHIF),
        .EN_REFCLK_MON            (EN_REFCLK_MON),
        .REF_COUNTS               (REF_COUNTS),
        .INTFBKDEL_SEL            (INTFBKDEL_SEL),
        .PMU_WAITFORLOCK          (PMU_WAITFORLOCK),
        .REF_OSC_CTRL             (REF_OSC_CTRL),
        .SIM_FLOAT_PRECISION      (SIM_FLOAT_PRECISION),
        .IPI_CMP                  (IPI_CMP),
        .CSET                     (CSET),
        .CRIPPLE                  (CRIPPLE),
        .IPP_CTRL                 (IPP_CTRL),
        .IPP_SEL                  (IPP_SEL),
        .BW_CTL_BIAS              (BW_CTL_BIAS),
        .V2I_PP_RES               (V2I_PP_RES),
        .KP_VCO                   (KP_VCO),
        .V2I_KVCO_SEL             (V2I_KVCO_SEL),
        .V2I_1V_EN                (V2I_1V_EN)
    ) u_pll (
        .rstn_i                   (rstn_i),
        .clki_i                   (clki_i),
        .usr_fbclk_i              (usr_fbclk_i),
        .phasedir_i               (phasedir_i),
        .phasestep_i              (phasestep_i),
        .phaseloadreg_i           (phaseloadreg_i),
        .phasesel_i               (phasesel_i),
        .enclkop_i                (enclkop_i),
        .enclkos_i                (enclkos_i),
        .enclkos2_i               (enclkos2_i),
        .enclkos3_i               (enclkos3_i),
        .enclkos4_i               (enclkos4_i),
        .enclkos5_i               (enclkos5_i),
        .clkop_o                  (clkop_o),
        .clkos_o                  (clkos_o),
        .clkos2_o                 (clkos2_o),
        .clkos3_o                 (clkos3_o),
        .clkos4_o                 (clkos4_o),
        .clkos5_o                 (clkos5_o),
        .lock_o                   (lock_o),
        .pllpd_en_n_i             (pllpd_en_n_i),
        .legacy_i                 (legacy_i),
        .refdetreset              (refdetreset),
        .refdetlos                (refdetlos),
        .lmmi_clk_i               (lmmi_clk_i),
        .lmmi_resetn_i            (lmmi_resetn_i),
        .lmmi_request_i           (lmmi_request_i),
        .lmmi_wr_rdn_i            (lmmi_wr_rdn_i),
        .lmmi_offset_i            (lmmi_offset_i),
        .lmmi_wdata_i             (lmmi_wdata_i),
        .lmmi_ready_o             (lmmi_ready_o),
        .lmmi_rdata_valid_o       (lmmi_rdata_valid_o),
        .lmmi_rdata_o             (lmmi_rdata_o),
        .apb_pclk_i               (apb_pclk_i),
        .apb_preset_n_i           (apb_preset_n_i),
        .apb_penable_i            (apb_penable_i),
        .apb_psel_i               (apb_psel_i),
        .apb_pwrite_i             (apb_pwrite_i),
        .apb_paddr_i              (apb_paddr_i),
        .apb_pwdata_i             (apb_pwdata_i),
        .apb_pready_o             (apb_pready_o),
        .apb_pslverr_o            (apb_pslverr_o),
        .apb_prdata_o             (apb_prdata_o)
    );

endmodule
